# Generated by Django 4.1.5 on 2023-01-26 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('token', models.CharField(max_length=6, unique=True, validators=[
                    django.core.validators.RegexValidator(
                        code='invalid_token',
                        message='Token can only contain alphabets and numerals',
                        regex='^[a-zA-Z0-9]{6}$',
                    )],
                )),
                ('clicks_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
